apiVersion: apps/v1
kind: Deployment
metadata:
  name: rkapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rkapp
  template:
    metadata:
      labels:
        app: rkapp
    spec:
      containers:
        - image: nginx
          imagePullPolicy: Always
          name: rkapp
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 80
            protocol: TCP
      restartPolicy: Always